# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "ThoughtVCS",
]

@typing.final
class ThoughtVCS:
    r"""
    Represents a simple version control system for managing branches and their commits.
    """
    def __new__(cls) -> ThoughtVCS:
        r"""
        Creates a new instance of `ThoughtVCS` with default branches.
        
        Returns:
            A new `ThoughtVCS` instance initialized with default branch data.
        """
    def commit(self, content: builtins.str, serial: builtins.int, estimated: builtins.int, branch: typing.Optional[builtins.str] = None, insert: builtins.bool = True) -> typing.Optional[builtins.int]:
        r"""
        Commits new content to a branch, creating the branch if necessary.
        
        Args:
            content: The content of the commit.
            serial: The serial number (1-based) for the commit.
            estimated: The estimated total number of commits for the branch.
            branch: The name of the branch, or None for the default branch.
            insert: Whether to create the branch if it does not exist.
        
        Returns:
            Some(new_commit_count) if the commit was added, or None otherwise.
        """
    def revise(self, content: builtins.str, serial: builtins.int, branch: typing.Optional[builtins.str]) -> typing.Optional[builtins.int]:
        r"""
        Revises the content of an existing commit in a branch.
        
        Args:
            content: The new content for the commit.
            serial: The serial number (1-based) of the commit to revise.
            branch: The name of the branch, or None for the default branch.
        
        Returns:
            Some(serial) if the commit was revised, or None otherwise.
        """
    def checkout(self, branch: builtins.str, serial: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Checks out a branch at a specific commit serial, truncating it to that point.
        
        Args:
            branch: The name of the branch to checkout.
            serial: The number of commits to include in the checked-out branch.
        
        Returns:
            Some(branch_name) if the checkout was successful, or None otherwise.
        """
    def export_branch(self, branch: typing.Optional[builtins.str] = None) -> builtins.list[builtins.str]:
        r"""
        Exports the list of commits for a given branch.
        
        This function retrieves all commits associated with the specified branch.
        If the branch does not exist, it returns an empty vector.
        
        Args:
            branch: An optional string representing the name of the branch.
                If None, the default branch is used.
        
        Returns:
            A vector of strings where each string represents a commit in the branch.
            If the branch does not exist, an empty vector is returned.
        """
    def export_branch_string(self, branch: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        Exports the list of commits as a formatted string.
        
        Args:
            branch: An optional string representing the name of the branch.
                If None, the default branch is used.
        
        Returns:
            A formatted string where each line represents a commit in the branch.
            If the branch does not exist, returns an empty string.
        """

