# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

__all__ = [
    "NovelBuilder",
    "text_to_xhtml_paragraphs",
]

@typing.final
class NovelBuilder:
    r"""A Python-exposed builder for creating EPUB novels."""
    def __new__(cls) -> NovelBuilder:
        r"""Creates a new uninitialized NovelBuilder instance."""
    def new_novel(self) -> NovelBuilder:
        r"""Initializes a new EPUB novel builder."""
    def set_title(self, title: builtins.str) -> NovelBuilder: ...
    def set_description(self, description: builtins.str) -> NovelBuilder:
        r"""Sets the novel description."""
    def add_author(self, author: builtins.str) -> NovelBuilder:
        r"""Adds an author to the novel metadata."""
    def add_chapter(self, title: builtins.str, content: builtins.str) -> NovelBuilder:
        r"""Adds a chapter with given title and content."""
    def add_cover_image(
        self, path: builtins.str | os.PathLike | pathlib.Path, source: builtins.str | os.PathLike | pathlib.Path
    ) -> NovelBuilder:
        r"""Adds a cover image from the given file path."""
    def add_metadata(self, key: builtins.str, value: builtins.str) -> NovelBuilder:
        r"""Adds custom metadata key-value pair to the novel."""
    def add_css(self, css: builtins.str) -> NovelBuilder:
        r"""Adds CSS styles to the novel."""
    def add_resource(
        self, path: builtins.str | os.PathLike | pathlib.Path, source: builtins.str | os.PathLike | pathlib.Path
    ) -> NovelBuilder:
        r"""Adds a resource file to the novel."""
    def add_font(self, font_family: builtins.str, source: builtins.str | os.PathLike | pathlib.Path) -> NovelBuilder:
        r"""Adds a font file to the novel."""
    def add_inline_toc(self) -> NovelBuilder:
        r"""Enables inline table of contents generation."""
    def export(self, path: builtins.str | os.PathLike | pathlib.Path) -> NovelBuilder:
        r"""Exports the built novel to the specified file path."""

def text_to_xhtml_paragraphs(source: builtins.str) -> builtins.str: ...
