# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "match_lines",
    "rate",
    "show_diff",
]

def match_lines(
    haystack: builtins.str, needle: builtins.str, match_precision: builtins.float = 0.9
) -> typing.Optional[builtins.str]:
    r"""Searches for a sequence of lines in `haystack` that approximately matches `needle`.

    This function uses the normalized Damerau-Levenshtein distance to find a matching block
    of lines with similarity score equal to or greater than `match_precision`.

    Args:
        haystack: The full text to search within.
        needle: The text pattern to find within the haystack.
        match_precision: Threshold for similarity score between 0.0 and 1.0 (default: 0.9).

    Returns:
        An Option containing the first matching block of lines if found,
        or None if no match meets the precision threshold.
    """

def rate(a: builtins.str, b: builtins.str) -> builtins.float:
    r"""Calculates the similarity rate between two strings using the normalized Damerau-Levenshtein distance.

    This function returns a float value between 0.0 and 1.0, where:
    - 1.0 means the strings are identical
    - 0.0 means the strings are completely different

    Args:
        a: The first string to compare.
        b: The second string to compare.

    Returns:
        A f64 value representing the similarity rate between the two input strings.
    """

def show_diff(a: builtins.str, b: builtins.str) -> builtins.str:
    r"""Generates a unified diff between two strings showing line-level changes.

    The diff output follows unified diff format conventions where:
    - Lines prefixed with `-` indicate deletions from `a`
    - Lines prefixed with `+` indicate additions from `b`
    - Unchanged lines are prefixed with a space

    Args:
        a: The original/old text content.
        b: The modified/new text content.

    Returns:
        A String containing the diff output with each line prefixed by its change type.
    """
