# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "SandboxSession",
    "VirtualFS",
]

@typing.final
class SandboxSession:
    r"""High-level sandbox: in-memory upper layer + optional read-only real-dir mounts.

    Tracks original file content on first mutation so `diff()` produces
    per-file unified diffs and `apply()` can flush changes to the real FS.
    """
    @staticmethod
    def with_mounts(mounts: typing.Mapping[builtins.str, builtins.str]) -> SandboxSession:
        r"""Create a sandbox session with read-only real-directory mounts.

        ``mounts`` maps virtual paths (e.g. ``"/project"``) to real directories.
        All writes go to the in-memory upper layer; reads fall through to the
        mounted real directories.
        """
    def read_text(self, path: builtins.str) -> builtins.str:
        r"""Read a text file from the sandbox, resolving mount prefixes."""
    def write_text(self, path: builtins.str, content: builtins.str) -> None:
        r"""Write text to a file, snapshotting the original before first mutation."""
    def read_bytes(self, path: builtins.str) -> builtins.list[builtins.int]:
        r"""Read a file and return its content as bytes."""
    def write_bytes(self, path: builtins.str, content: typing.Sequence[builtins.int]) -> None:
        r"""Write raw bytes to a file, snapshotting the original before first mutation."""
    def list_dir(self, path: builtins.str) -> builtins.list[builtins.str]:
        r"""List immediate children of a directory."""
    def walk_dir(self, path: builtins.str) -> builtins.list[builtins.str]:
        r"""Recursively walk a directory, returning all descendant paths."""
    def exists(self, path: builtins.str) -> builtins.bool:
        r"""Check whether a path exists in the sandbox."""
    def is_file(self, path: builtins.str) -> builtins.bool:
        r"""Check whether a path is a file."""
    def is_dir(self, path: builtins.str) -> builtins.bool:
        r"""Check whether a path is a directory."""
    def create_dir(self, path: builtins.str) -> None:
        r"""Create a single directory level."""
    def create_dir_all(self, path: builtins.str) -> None:
        r"""Create a directory and all missing ancestors."""
    def remove_file(self, path: builtins.str) -> None:
        r"""Remove a single file, snapshotting its content first."""
    def remove_dir_all(self, path: builtins.str) -> None:
        r"""Remove a directory and all its contents."""
    def copy_file(self, src: builtins.str, dst: builtins.str) -> None:
        r"""Copy a file from *src* to *dst*, snapshotting *dst* first."""
    def rename(self, src: builtins.str, dst: builtins.str) -> None:
        r"""Move a file from *src* to *dst*, snapshotting both first."""
    def abs_path(self, path: builtins.str) -> builtins.str:
        r"""Return the resolved absolute path string within the VFS."""
    def diff(self) -> dict:
        r"""Return ``{virtual_path: unified_diff, ...}`` for every mutated file."""
    def apply(self) -> None:
        r"""Flush mutations from the in-memory layer back to the real filesystem using the mount mappings.

        Only files that were written through the session are flushed.
        New files are created under the matching mount's real directory;
        existing files are overwritten.
        """
    def reset(self) -> None:
        r"""Clear tracked originals and written paths so the next ``diff()`` captures only fresh changes."""
    def root_path(self) -> builtins.str:
        r"""The virtual root path string. Returns ``"/"`` when the overlay root has no explicit path."""
    def mounts(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""Copy of the current mount mappings."""

@typing.final
class VirtualFS:
    r"""Thin wrapper around [`VfsPath`] exposing filesystem operations to Python."""
    @staticmethod
    def from_memory() -> VirtualFS:
        r"""Create an empty in-memory virtual filesystem."""
    @staticmethod
    def from_physical(root: builtins.str) -> VirtualFS:
        r"""Wrap a real directory as a read-only virtual filesystem."""
    @staticmethod
    def from_overlay(real_roots: typing.Sequence[builtins.str]) -> VirtualFS:
        r"""Layer an in-memory upper layer over read-only real directories.

        Writes go to the in-memory layer; reads fall through to the real dirs.
        """
    def read_text(self, path: builtins.str) -> builtins.str:
        r"""Read a text file and return its content as a string."""
    def write_text(self, path: builtins.str, content: builtins.str) -> None:
        r"""Write text content to a file, creating parent directories as needed."""
    def read_bytes(self, path: builtins.str) -> builtins.list[builtins.int]:
        r"""Read a file and return its content as bytes."""
    def write_bytes(self, path: builtins.str, content: typing.Sequence[builtins.int]) -> None:
        r"""Write raw bytes to a file, creating parent directories as needed."""
    def list_dir(self, path: builtins.str) -> builtins.list[builtins.str]:
        r"""List immediate children of a directory, returning filenames."""
    def walk_dir(self, path: builtins.str) -> builtins.list[builtins.str]:
        r"""Recursively walk a directory, returning all descendant paths."""
    def exists(self, path: builtins.str) -> builtins.bool:
        r"""Check whether a path exists."""
    def is_file(self, path: builtins.str) -> builtins.bool:
        r"""Check whether a path is a file."""
    def is_dir(self, path: builtins.str) -> builtins.bool:
        r"""Check whether a path is a directory."""
    def create_dir(self, path: builtins.str) -> None:
        r"""Create a single directory level at the given path."""
    def create_dir_all(self, path: builtins.str) -> None:
        r"""Create a directory and all missing ancestors."""
    def remove_file(self, path: builtins.str) -> None:
        r"""Remove a single file."""
    def remove_dir_all(self, path: builtins.str) -> None:
        r"""Remove a directory and all its contents."""
    def copy_file(self, src: builtins.str, dst: builtins.str) -> None:
        r"""Copy a file from *src* to *dst*, creating parent dirs for *dst*."""
    def rename(self, src: builtins.str, dst: builtins.str) -> None:
        r"""Move (rename) a file from *src* to *dst*."""
    def abs_path(self, path: builtins.str) -> builtins.str:
        r"""Return the resolved absolute path string within the VFS."""
