# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "CheckPointStore",
    "CheckpointService",
    "prune_stores",
]

@typing.final
class CheckPointStore:
    r"""
    Stores checkpoint information for a specific worktree directory.
    
    This class manages the shadow repository and provides methods for
    saving checkpoints, rolling back files, and retrieving commit history.
    """
    @property
    def workspace(self) -> pathlib.Path:
        r"""
        The worktree directory being tracked.
        """
    def save(self, commit_msg: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        Saves the current state of the worktree as a new commit.
        
        This method stages all changes in the worktree directory and creates a new commit
        in the shadow repository. It acts as a checkpoint that can later be restored.
        
        Args:
            commit_msg: Optional commit message; defaults to empty string if not provided.
        
        Returns:
            The commit ID (OID) as a string.
        
        Note:
            If there are no changes to commit, this method returns the ID of the last commit (the HEAD).
        """
    def head(self) -> builtins.str:
        r"""
        Retrieves the ID of the current HEAD commit.
        
        This method retrieves the ID of the current HEAD commit in the shadow repository.
        
        Returns:
            The commit ID (OID) as a string.
        """
    def commits(self) -> builtins.list[builtins.str]:
        r"""
        Lists all commit IDs in the shadow repository's history.
        
        This method retrieves the complete commit history from the current HEAD
        backwards through the parent commits. The commits are returned in reverse
        chronological order (newest first).
        
        Returns:
            A list of commit IDs (OIDs as strings) in reverse chronological order.
        """
    def reset(self, commit_id: builtins.str) -> None:
        r"""
        Resets the worktree to a specific commit.
        
        Performs a hard reset of the worktree directory to match the state at the specified commit.
        This discards all changes in the working directory and index, making them match the commit.
        
        Args:
            commit_id: The commit ID (OID as string) to reset to.
        """
    def rollback(self, commit_id: builtins.str, file_path: builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Restores a specific file from a commit.
        
        This rolls back a single file to its state at the specified commit,
        checking out that file from the commit's tree.
        
        Args:
            commit_id: The commit ID (OID as string) to restore from.
            file_path: The relative path to the file within the worktree.
        """
    def get_file_diff(self, commit_id: builtins.str, file_path: builtins.str | os.PathLike | pathlib.Path) -> builtins.str:
        r"""
        Retrieves the diff for a specific file at a given commit.
        
        Compares the file state at the specified commit with its state in the parent commit,
        returning a patch-format diff string. If the commit has no parent (initial commit),
        it compares against an empty tree.
        
        Args:
            commit_id: The commit ID (OID as string) to get the diff from.
            file_path: The relative path to the file within the worktree.
        
        Returns:
            A string containing the unified diff in patch format.
        """
    def get_status(self) -> builtins.list[builtins.str]:
        r"""
        Retrieves the status of the worktree.
        
        Returns a list of file paths that have changed since the last commit.
        
        Returns:
            A list of file paths that have changed since the last commit.
        """

@typing.final
class CheckpointService:
    r"""
    Manages shadow Git repositories for file checkpointing.
    
    A shadow repository manager creates and maintains separate bare Git repositories
    for each worktree directory. This enables independent version control and checkpointing
    without interfering with any existing Git repositories in the worktree.
    """
    def get_store(self, worktree_dir: builtins.str | os.PathLike | pathlib.Path) -> CheckPointStore:
        r"""
        Gets or creates a shadow repository for the given worktree directory.
        
        This method first checks the cache for an existing repository. If not found,
        it either opens an existing bare repository from disk or creates a new one.
        
        Args:
            worktree_dir: The directory to be tracked by the shadow repository.
        
        Returns:
            A CheckPointStore instance for the specified worktree.
        """
    def __new__(cls, stores_root: builtins.str | os.PathLike | pathlib.Path, cache_size: builtins.int = 10) -> CheckpointService:
        r"""
        Creates a new CheckpointService instance.
        
        Initializes a shadow repository manager with the specified root directory
        and cache size. Creates the shadow root directory if it doesn't exist.
        
        Args:
            stores_root: The root directory where shadow repositories will be stored.
            cache_size: Maximum number of repositories to keep in the in-memory cache.
        
        Returns:
            A new CheckpointService instance.
        """
    def workspaces(self) -> builtins.list[pathlib.Path]:
        r"""
        Returns a list of all managed workspaces.
        
        Returns:
            A list of paths to managed workspace directories.
        """
    def prune_invalid(self) -> None:
        r"""
        Prunes stores which manage an invalid workspace.
        
        Returns:
            PyResult<()> indicating success.
        """

def prune_stores(stores_root: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Removes all store repositories under the given root path whose working directories no longer exist.
    
    This function:
    1. Iterates through all directories under the stores_root
    2. Attempts to open each as a git repository
    3. Checks if the repository's working directory still exists
    4. If the working directory doesn't exist, removes the entire repository directory
    
    This is used to clean up shadow repositories whose original workspaces have been deleted.
    """

