# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "Skill",
    "SkillMeta",
    "SkillRegistry",
]

@typing.final
class Skill:
    r"""A loaded skill: metadata + markdown content."""
    @property
    def name(self) -> builtins.str:
        r"""Skill identifier (from frontmatter `name`, or filename stem)."""
    @property
    def description(self) -> builtins.str:
        r"""Human-readable description."""
    @property
    def tags(self) -> builtins.list[builtins.str]:
        r"""Tags for search/filtering."""
    @property
    def content(self) -> builtins.str:
        r"""Markdown body (everything after the frontmatter)."""
    @property
    def path(self) -> builtins.str:
        r"""Source file path (relative to scan root)."""
    @property
    def briefing(self) -> builtins.str:
        r"""Briefing of the skill: ``name: description``, used as an LLM option summary."""
    def __new__(
        cls,
        name: builtins.str,
        description: builtins.str,
        tags: typing.Sequence[builtins.str],
        content: builtins.str,
        path: builtins.str,
    ) -> Skill: ...
    def meta(self) -> SkillMeta:
        r"""Lightweight representation: name + description + tags (no content)."""

@typing.final
class SkillMeta:
    r"""Lightweight skill metadata (no content body)."""
    @property
    def name(self) -> builtins.str: ...
    @property
    def description(self) -> builtins.str: ...
    @property
    def tags(self) -> builtins.list[builtins.str]: ...
    @property
    def path(self) -> builtins.str: ...

@typing.final
class SkillRegistry:
    r"""The process-wide skill library: one in-memory copy of every loaded skill.

    Python roles store skill **names** (plain ``str``) and resolve real
    ``Skill`` objects through this library at runtime. ``instance()`` hands out
    the library itself — every handle shares the same store, so a skill file is
    parsed once per process — and the loaders return the names they made
    available (a cached name is reported, never read again).
    """
    @staticmethod
    def instance() -> SkillRegistry:
        r"""The process-wide library. Every handle shares the same in-memory skills."""
    def load_scanned(self, roots: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]:
        r"""Load every `.md` file found under each root into the library.

        Walks each root recursively and parses YAML frontmatter plus markdown
        body (`<root>/<name>/SKILL.md` and flat `<root>/<name>.md` both match);
        a name already in the library keeps its first copy.

        Args:
            roots: Directories to scan.

        Returns:
            The names those roots provide, ordered. A name already in the library
            is reported too, without its file being read again.

        Raises:
            FileNotFoundError: One of the roots is not an existing directory
                (nothing is loaded in that case).
        """
    def load_by_name(
        self, names: typing.Sequence[builtins.str], roots: typing.Sequence[builtins.str]
    ) -> builtins.list[builtins.str]:
        r"""Resolve each name through `roots` and load the hits into the library.

        Tries each root in order — `<root>/<name>/SKILL.md` first, then
        `<root>/<name>.md` (direct path reads, no directory walk). Names already
        in the library keep their first copy and are not read again; names no
        root resolves are skipped.

        Args:
            names: Skill names to resolve; duplicates collapse.
            roots: Lookup roots, tried in order.

        Returns:
            The names that are now in the library, in argument order. A name
            already in the library is reported too, without being read again.
        """
    def add(self, skills: typing.Sequence[Skill]) -> SkillRegistry:
        r"""Merge already-parsed skills into the library; the first copy of a name wins.

        Args:
            skills: Skill objects to add.

        Returns:
            The library, for chaining.
        """
    def remove(self, names: typing.Sequence[builtins.str]) -> SkillRegistry:
        r"""Drop the named skills, so their files are read again on the next load.

        Args:
            names: Skill names to drop.

        Returns:
            The library, for chaining.
        """
    def clear(self) -> SkillRegistry:
        r"""Drop every loaded skill.

        Returns:
            The library, for chaining.
        """
    def get(self, name: builtins.str) -> Skill | None:
        r"""Return a skill by exact name, or ``None``."""
    def get_many(self, names: typing.Sequence[builtins.str]) -> builtins.list[Skill]:
        r"""Return skills for the given names, silently skipping missing ones."""
    def all(self) -> builtins.list[Skill]:
        r"""Return every loaded skill, ordered by name."""
    def names(self) -> builtins.list[builtins.str]:
        r"""Return every loaded skill name, ordered."""
    def search(
        self, query: builtins.str, names: typing.Sequence[builtins.str] | None = None, in_content: builtins.bool = False
    ) -> builtins.list[Skill]:
        r"""Search the library by keyword against name, tags, description, and content.

        Args:
            query: Search term (case-insensitive).
            names: Restrict the search to these skill names. None searches every
                loaded skill.
            in_content: Whether to also search within the skill content body.

        Returns:
            Matching skills, ordered by relevance (name/tag match first).
        """
    def __contains__(self, name: builtins.str) -> builtins.bool: ...
    def __len__(self) -> builtins.int: ...
