# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "Skill",
    "SkillMeta",
    "SkillRegistry",
    "fetch_skill",
    "get_skill",
    "scan_skills",
    "search_skills",
]

@typing.final
class Skill:
    r"""A loaded skill: metadata + markdown content."""
    @property
    def name(self) -> builtins.str:
        r"""Skill identifier (from frontmatter `name`, or filename stem)."""
    @property
    def description(self) -> builtins.str:
        r"""Human-readable description."""
    @property
    def tags(self) -> builtins.list[builtins.str]:
        r"""Tags for search/filtering."""
    @property
    def content(self) -> builtins.str:
        r"""Markdown body (everything after the frontmatter)."""
    @property
    def path(self) -> builtins.str:
        r"""Source file path (relative to scan root)."""
    @property
    def briefing(self) -> builtins.str:
        r"""Briefing of the skill: ``name: description``, used as an LLM option summary."""
    def __new__(
        cls,
        name: builtins.str,
        description: builtins.str,
        tags: typing.Sequence[builtins.str],
        content: builtins.str,
        path: builtins.str,
    ) -> Skill: ...
    def meta(self) -> SkillMeta:
        r"""Lightweight representation: name + description + tags (no content)."""

@typing.final
class SkillMeta:
    r"""Lightweight skill metadata (no content body)."""
    @property
    def name(self) -> builtins.str: ...
    @property
    def description(self) -> builtins.str: ...
    @property
    def tags(self) -> builtins.list[builtins.str]: ...
    @property
    def path(self) -> builtins.str: ...

@typing.final
class SkillRegistry:
    r"""Process-wide registry that owns all loaded ``Skill`` objects.

    Python roles store skill **names** (plain ``str``) and resolve real
    ``Skill`` objects through this registry at runtime.
    """
    def __new__(cls) -> SkillRegistry: ...
    def register(self, skills: typing.Sequence[Skill]) -> builtins.int:
        r"""Register skills. Returns count of newly added entries."""
    def unregister(self, names: typing.Sequence[builtins.str]) -> builtins.int:
        r"""Remove skills by name. Returns count removed."""
    def clear(self) -> None:
        r"""Remove all registered skills."""
    def get(self, name: builtins.str) -> Skill | None:
        r"""Return a skill by exact name, or ``None``."""
    def get_many(self, names: typing.Sequence[builtins.str]) -> builtins.list[Skill]:
        r"""Return skills for the given names, silently skipping missing."""
    def all(self) -> builtins.list[Skill]:
        r"""Return every registered skill."""
    def names(self) -> builtins.list[builtins.str]:
        r"""Return every registered skill name."""
    def __contains__(self, name: builtins.str) -> builtins.bool: ...
    def __len__(self) -> builtins.int: ...

def fetch_skill(root: builtins.str, name: builtins.str) -> Skill | None:
    r"""Fetch a single skill by name from a skill directory without scanning.

    Tries the agent-skills convention `<root>/<name>/SKILL.md` first, then the
    flat convention `<root>/<name>.md`. Direct path reads only — no directory walk.

    Args:
        root: Skill directory root to resolve the name against.
        name: Skill name to fetch (a plain name; path separators are rejected).

    Returns:
        The parsed Skill, or None when no convention path holds a readable
        `.md` file for this name.
    """

def get_skill(name: builtins.str, skills: typing.Sequence[Skill]) -> Skill | None:
    r"""Get a skill by exact name.

    Args:
        name: Exact skill name to look up.
        skills: List of skills to search.

    Returns:
        The matching Skill, or None if not found.
    """

def scan_skills(path: builtins.str) -> builtins.list[Skill]:
    r"""Scan a directory for `.md` skill files and return parsed Skill objects.

    Walks the directory recursively, reads every `.md` file, parses YAML
    frontmatter for metadata, and collects the markdown body as content.

    Args:
        path: Root directory to scan.

    Returns:
        List of Skill objects discovered from the directory.
    """

def search_skills(
    query: builtins.str, skills: typing.Sequence[Skill], in_content: builtins.bool = False
) -> builtins.list[Skill]:
    r"""Search skills by keyword matching against name, description, tags, and content.

    Args:
        query: Search term (case-insensitive).
        skills: List of skills to search through.
        in_content: Whether to also search within the skill content body.

    Returns:
        Skills matching the query, ordered by relevance (name/tag match first).
    """
