# This file is automatically generated by pyo3_stub_gen

import builtins
import enum
import os
import pathlib
import typing

__all__ = [
    "CONFIG",
    "ROUTER",
    "TEMPLATE_MANAGER",
    "Config",
    "DebugConfig",
    "DeploymentConfig",
    "EmbeddingConfig",
    "EmitterConfig",
    "Event",
    "GeneralConfig",
    "LLMConfig",
    "Logger",
    "ProviderConfig",
    "ProviderType",
    "Router",
    "RoutingConfig",
    "SecretStr",
    "TaskStatus",
    "TemplateConfig",
    "TemplateManager",
    "TemplateManagerConfig",
    "blake3_hash",
    "detect_language",
    "extra_satisfied",
    "extras_satisfied",
    "is_arabic",
    "is_chinese",
    "is_dutch",
    "is_english",
    "is_french",
    "is_german",
    "is_hindi",
    "is_installed",
    "is_italian",
    "is_japanese",
    "is_korean",
    "is_likely_text",
    "is_portuguese",
    "is_russian",
    "is_swedish",
    "is_turkish",
    "is_vietnamese",
    "list_installed",
    "logger",
    "split_into_chunks",
    "split_sentence_bounds",
    "split_word_bounds",
    "tokens_of",
    "word_count",
]
_T = typing.TypeVar("_T")
CONFIG: Config
ROUTER: Router
TEMPLATE_MANAGER: TemplateManager
logger: Logger

@typing.final
class Config:
    r"""Configuration structure containing all system components."""
    @property
    def embedding(self) -> EmbeddingConfig:
        r"""Embedding configuration parameters."""
    @property
    def llm(self) -> LLMConfig:
        r"""Language Learning Model settings with validation rules."""
    @property
    def debug(self) -> DebugConfig:
        r"""Debug settings containing log level and verbosity."""
    @property
    def templates(self) -> TemplateConfig:
        r"""Template paths/names for various operations."""
    @property
    def template_manager(self) -> TemplateManagerConfig:
        r"""Template loading and management settings."""
    @property
    def routing(self) -> RoutingConfig:
        r"""Request routing and load balancing settings."""
    @property
    def general(self) -> GeneralConfig:
        r"""Global behavior configuration options."""
    @property
    def emitter(self) -> EmitterConfig:
        r"""Event emission control settings."""
    def load(self, name: str, config_cls: typing.Type[_T]) -> _T:
        r"""Load configuration data for a given section name and instantiate a Python class."""

@typing.final
class DebugConfig:
    @property
    def log_level(self) -> builtins.str: ...
    @log_level.setter
    def log_level(self, value: builtins.str) -> None: ...
    @property
    def log_dir(self) -> typing.Optional[pathlib.Path]: ...
    @log_dir.setter
    def log_dir(self, value: typing.Optional[pathlib.Path]) -> None: ...
    @property
    def rotation(self) -> typing.Optional[builtins.str]: ...
    @rotation.setter
    def rotation(self, value: typing.Optional[builtins.str]) -> None: ...

@typing.final
class DeploymentConfig:
    r"""Configuration for a specific deployment.

    Defines the identity, grouping, and rate limits for a deployed service instance.
    """
    @property
    def id(self) -> builtins.str:
        r"""Unique identifier for the deployment."""
    @property
    def group(self) -> builtins.str:
        r"""Name of the route group this deployment belongs to."""
    @property
    def tpm(self) -> typing.Optional[builtins.int]:
        r"""Optional quota limit for tokens per minute (TPM)."""
    @property
    def rpm(self) -> typing.Optional[builtins.int]:
        r"""Optional quota limit for requests per minute (RPM)."""

@typing.final
class EmbeddingConfig:
    r"""Embedding configuration structure."""
    @property
    def send_to(self) -> typing.Optional[builtins.str]: ...
    @send_to.setter
    def send_to(self, value: typing.Optional[builtins.str]) -> None: ...

@typing.final
class EmitterConfig:
    r"""Pymitter configuration structure.

    Contains settings for controlling event emission and listener behavior
    """
    @property
    def delimiter(self) -> builtins.str:
        r"""The delimiter used to separate the event name into segments."""
    @delimiter.setter
    def delimiter(self, value: builtins.str) -> None:
        r"""The delimiter used to separate the event name into segments."""

@typing.final
class Event:
    @property
    def segments(self) -> builtins.list[builtins.str]: ...
    def __new__(cls, segments: typing.Optional[typing.Sequence[builtins.str]] = None) -> Event: ...
    @staticmethod
    def instantiate_from(event: typing.List[str] | str | Event) -> Event: ...
    @staticmethod
    def quick_instantiate(event: typing.List[str] | str | Event) -> Event: ...
    def derive(self, event: typing.List[str] | str | Event) -> Event: ...
    def collapse(self) -> builtins.str: ...
    def fork(self) -> Event: ...
    def push(self, segment: TaskStatus | str) -> Event: ...
    def push_wildcard(self) -> Event: ...
    def push_pending(self) -> Event: ...
    def push_running(self) -> Event: ...
    def push_finished(self) -> Event: ...
    def push_failed(self) -> Event: ...
    def push_cancelled(self) -> Event: ...
    def pop(self) -> typing.Optional[builtins.str]: ...
    def clear(self) -> Event: ...
    def concat(self, event: typing.List[str] | str | Event) -> Event: ...
    def __hash__(self) -> builtins.int: ...
    def __richcmp__(self, other: typing.Any, op: int) -> builtins.bool: ...

@typing.final
class GeneralConfig:
    r"""General configuration structure for application-wide settings."""
    @property
    def use_json_repair(self) -> builtins.bool:
        r"""Whether to automatically repair malformed JSON."""
    @use_json_repair.setter
    def use_json_repair(self, value: builtins.bool) -> None:
        r"""Whether to automatically repair malformed JSON."""

@typing.final
class LLMConfig:
    r"""Configuration for Language Learning Models (LLMs) like OpenAI's GPT.

    This structure contains all parameters needed to configure and interact with LLM services.
    All fields are optional to allow partial configuration from different sources.
    """
    @property
    def send_to(self) -> typing.Optional[builtins.str]: ...
    @send_to.setter
    def send_to(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def temperature(self) -> typing.Optional[builtins.float]: ...
    @temperature.setter
    def temperature(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def top_p(self) -> typing.Optional[builtins.float]: ...
    @top_p.setter
    def top_p(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def stream(self) -> builtins.bool: ...
    @stream.setter
    def stream(self, value: builtins.bool) -> None: ...
    @property
    def max_completion_tokens(self) -> typing.Optional[builtins.int]: ...
    @max_completion_tokens.setter
    def max_completion_tokens(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def presence_penalty(self) -> typing.Optional[builtins.float]: ...
    @presence_penalty.setter
    def presence_penalty(self, value: typing.Optional[builtins.float]) -> None: ...
    @property
    def frequency_penalty(self) -> typing.Optional[builtins.float]: ...
    @frequency_penalty.setter
    def frequency_penalty(self, value: typing.Optional[builtins.float]) -> None: ...

@typing.final
class Logger:
    def info(self, msg: builtins.str) -> None: ...
    def debug(self, msg: builtins.str) -> None: ...
    def error(self, msg: builtins.str) -> None: ...
    def warn(self, msg: builtins.str) -> None: ...
    def trace(self, msg: builtins.str) -> None: ...

@typing.final
class ProviderConfig:
    r"""Configuration for a specific provider.

    Contains the necessary details to connect to and authenticate with a service provider.
    """
    @property
    def ptype(self) -> ProviderType:
        r"""The type of the provider (e.g., OpenAI, Anthropic)."""
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""Optional name identifier for the provider instance."""
    @property
    def key(self) -> typing.Optional[SecretStr]:
        r"""Optional authentication key for the provider API."""
    @property
    def base_url(self) -> typing.Optional[builtins.str]:
        r"""Optional URL endpoint for the provider's API. Must be a valid URL if provided."""

@typing.final
class Router:
    def completion(
        self,
        send_to: builtins.str,
        message: builtins.str,
        stream: builtins.bool = False,
        top_p: typing.Optional[builtins.float] = None,
        temperature: typing.Optional[builtins.float] = None,
        max_completion_tokens: typing.Optional[builtins.int] = None,
        presence_penalty: typing.Optional[builtins.float] = None,
        frequency_penalty: typing.Optional[builtins.float] = None,
    ) -> typing.Awaitable[str]:
        r"""Sends a completion request to the specified group and returns the full response.

        Note: Although a 'stream' argument exists for protocol compatibility, this
        implementation always aggregates the full response before returning.
        It does not yield chunks asynchronously.

        Args:
            send_to (str): The router group name.
            message (str): The user prompt content.
            stream (bool): Logical flag for compatibility. No performance difference. Defaults to False.
            top_p (Optional[float]): Nucleus sampling parameter. Defaults to 1.0 if None.
            temperature (Optional[float]): Controls randomness. Defaults to 0.7 if None.
            max_completion_tokens (Optional[int]): Maximum tokens to generate. Defaults to 2048 if None.
            presence_penalty (Optional[float]): Penalizes new tokens based on presence. Defaults to 0.0 if None.
            frequency_penalty (Optional[float]): Penalizes new tokens based on frequency. Defaults to 0.0 if None.

        Returns:
            str: The complete aggregated response content.
        """
    def embedding(
        self, send_to: builtins.str, texts: typing.Sequence[builtins.str]
    ) -> typing.Awaitable[typing.List[typing.List[float]]]:
        r"""Sends an embedding request to the specified group.

        Args:
            send_to (str): The router group name to route the embedding request.
            texts (List[str]): A list of text strings to generate embeddings for.

        Returns:
            List[List[float]]: A list of embedding vectors corresponding to the input texts.
        """
    def add_provider(
        self,
        provider_type: ProviderType,
        name: typing.Optional[builtins.str] = None,
        api_key: typing.Optional[SecretStr] = None,
        endpoint: typing.Optional[builtins.str] = None,
    ) -> typing.Awaitable[None]:
        r"""Adds a provider to the router.

        This method registers a new provider with both the completion and embedding routers.

        Args:
            provider_type (ProviderType): The type of the provider (e.g., OpenAI, Anthropic).
            name (Optional[str]): Optional custom name for the provider.
            api_key (Optional[SecretStr]): Optional API key for authentication.
            endpoint (Optional[str]): Optional custom API endpoint URL.

        Returns:
            None: This is an asynchronous operation that modifies the router state.
        """
    def add_completion_model(
        self,
        group: builtins.str,
        model_identifier: builtins.str,
        rpm: typing.Optional[builtins.int] = None,
        tpm: typing.Optional[builtins.int] = None,
    ) -> typing.Awaitable[None]:
        r"""Adds a completion model to the specified group.

        Registers a new model identifier within a specific routing group for completion tasks.

        Args:
            group (str): The target router group name.
            model_identifier (str): The unique identifier of the model to be added.
            rpm (Optional[int]): Optional requests per minute limit.
            tpm (Optional[int]): Optional tokens per minute limit.

        Returns:
            None: This is an asynchronous operation that modifies the router state.
        """
    def add_embedding_model(
        self,
        group: builtins.str,
        model_identifier: builtins.str,
        rpm: typing.Optional[builtins.int] = None,
        tpm: typing.Optional[builtins.int] = None,
    ) -> typing.Awaitable[None]:
        r"""Adds an embedding model to the specified group.

        Registers a new model identifier within a specific routing group for embedding tasks.

        Args:
            group (str): The target router group name.
            model_identifier (str): The unique identifier of the model to be added.
            rpm (Optional[Quota]): Optional requests per minute limit.
            tpm (Optional[Quota]): Optional tokens per minute limit.

        Returns:
            None: This is an asynchronous operation that modifies the router state.
        """

@typing.final
class RoutingConfig:
    r"""Routing configuration structure for controlling request dispatching behavior.

    Manages the list of available providers and their corresponding deployments
    to handle load balancing and request routing.
    """
    @property
    def providers(self) -> builtins.list[ProviderConfig]:
        r"""List of configured providers available for routing."""
    @property
    def embedding_deployments(self) -> builtins.list[DeploymentConfig]:
        r"""List of configured embedding model deployments associated with the providers."""
    @property
    def completion_deployments(self) -> builtins.list[DeploymentConfig]:
        r"""List of configured completion model deployments associated with the providers."""
    @property
    def cache_database_path(self) -> typing.Optional[pathlib.Path]:
        r"""Path to the cache database file."""

@typing.final
class SecretStr:
    def __new__(cls, source: builtins.str) -> SecretStr: ...
    def get_secret_value(self) -> builtins.str: ...

@typing.final
class TemplateConfig:
    r"""Template configuration structure."""
    @property
    def mapping_template(self) -> builtins.str: ...
    @mapping_template.setter
    def mapping_template(self, value: builtins.str) -> None: ...
    @property
    def task_briefing_template(self) -> builtins.str:
        r"""The name of the task briefing template which will be used to brief a task."""
    @task_briefing_template.setter
    def task_briefing_template(self, value: builtins.str) -> None:
        r"""The name of the task briefing template which will be used to brief a task."""
    @property
    def dependencies_template(self) -> builtins.str:
        r"""The name of the dependencies template which will be used to manage dependencies."""
    @dependencies_template.setter
    def dependencies_template(self, value: builtins.str) -> None:
        r"""The name of the dependencies template which will be used to manage dependencies."""
    @property
    def make_choice_template(self) -> builtins.str:
        r"""The name of the make choice template which will be used to make a choice."""
    @make_choice_template.setter
    def make_choice_template(self, value: builtins.str) -> None:
        r"""The name of the make choice template which will be used to make a choice."""
    @property
    def make_judgment_template(self) -> builtins.str:
        r"""The name of the make judgment template which will be used to make a judgment."""
    @make_judgment_template.setter
    def make_judgment_template(self, value: builtins.str) -> None:
        r"""The name of the make judgment template which will be used to make a judgment."""
    @property
    def code_string_template(self) -> builtins.str:
        r"""The name of the code string template which will be used to generate a code string."""
    @code_string_template.setter
    def code_string_template(self, value: builtins.str) -> None:
        r"""The name of the code string template which will be used to generate a code string."""
    @property
    def code_snippet_template(self) -> builtins.str:
        r"""The name of the code snippet template which will be used to generate a code snippet."""
    @code_snippet_template.setter
    def code_snippet_template(self, value: builtins.str) -> None:
        r"""The name of the code snippet template which will be used to generate a code snippet."""
    @property
    def generic_string_template(self) -> builtins.str:
        r"""The name of the generic string template which will be used to review a string."""
    @generic_string_template.setter
    def generic_string_template(self, value: builtins.str) -> None:
        r"""The name of the generic string template which will be used to review a string."""
    @property
    def co_validation_template(self) -> builtins.str:
        r"""The name of the co-validation template which will be used to co-validate a string."""
    @co_validation_template.setter
    def co_validation_template(self, value: builtins.str) -> None:
        r"""The name of the co-validation template which will be used to co-validate a string."""
    @property
    def liststr_template(self) -> builtins.str:
        r"""The name of the liststr template which will be used to display a list of strings."""
    @liststr_template.setter
    def liststr_template(self, value: builtins.str) -> None:
        r"""The name of the liststr template which will be used to display a list of strings."""
    @property
    def pathstr_template(self) -> builtins.str:
        r"""The name of the pathstr template which will be used to acquire a path of strings."""
    @pathstr_template.setter
    def pathstr_template(self, value: builtins.str) -> None:
        r"""The name of the pathstr template which will be used to acquire a path of strings."""
    @property
    def create_json_obj_template(self) -> builtins.str:
        r"""The name of the create json object template which will be used to create a json object."""
    @create_json_obj_template.setter
    def create_json_obj_template(self, value: builtins.str) -> None:
        r"""The name of the create json object template which will be used to create a json object."""

@typing.final
class TemplateManager:
    r"""Python bindings for the TemplateManager struct."""
    @property
    def templates_stores(self) -> builtins.list[pathlib.Path]: ...
    @property
    def template_count(self) -> builtins.int:
        r"""Create a new TemplateManager instance."""
    def add_store(
        self, source: builtins.str | os.PathLike | pathlib.Path, rediscovery: builtins.bool = False
    ) -> TemplateManager:
        r"""Add a template directory to the list of template directories."""
    def add_stores(
        self, sources: typing.Sequence[builtins.str | os.PathLike | pathlib.Path], rediscovery: builtins.bool = False
    ) -> TemplateManager: ...
    def discover_templates(self) -> TemplateManager:
        r"""Discover the templates in the template directories."""
    @typing.overload
    def render_template(self, name: str, data: typing.Dict[str, typing.Any]) -> str: ...
    @typing.overload
    def render_template(self, name: str, data: typing.List[typing.Dict[str, typing.Any]]) -> typing.List[str]: ...
    @typing.overload
    def render_template_raw(self, name: str, template: str, data: typing.Dict[str, typing.Any]) -> str: ...
    @typing.overload
    def render_template_raw(
        self, name: str, template: str, data: typing.List[typing.Dict[str, typing.Any]]
    ) -> typing.List[str]: ...

@typing.final
class TemplateManagerConfig:
    @property
    def template_stores(self) -> builtins.list[pathlib.Path]:
        r"""The directory containing the templates."""
    @template_stores.setter
    def template_stores(self, value: builtins.list[pathlib.Path]) -> None:
        r"""The directory containing the templates."""
    @property
    def active_loading(self) -> builtins.bool:
        r"""Whether to enable active loading of templates."""
    @active_loading.setter
    def active_loading(self, value: builtins.bool) -> None:
        r"""Whether to enable active loading of templates."""
    @property
    def template_suffix(self) -> builtins.str:
        r"""The suffix of the templates."""
    @template_suffix.setter
    def template_suffix(self, value: builtins.str) -> None:
        r"""The suffix of the templates."""

@typing.final
class ProviderType(enum.Enum):
    OpenAI = ...
    OpenAICompatible = ...
    Dummy = ...

@typing.final
class TaskStatus(enum.Enum):
    Pending = ...
    Running = ...
    Finished = ...
    Failed = ...
    Cancelled = ...

    def __new__(cls, variant: builtins.int) -> TaskStatus: ...
    def __setstate__(self, state: bytes) -> None: ...
    def __getstate__(self) -> bytes: ...
    def __getnewargs__(self) -> tuple[builtins.int]: ...

def blake3_hash(content: bytes) -> builtins.str:
    r"""Calculate hash with blake3 as backbone."""

def detect_language(string: builtins.str) -> builtins.str:
    r"""Detect the language of a string."""

def extra_satisfied(pkg_name: builtins.str, extra_name: builtins.str) -> builtins.bool:
    r"""Checks if a specific extra (optional dependency) of a Python package is satisfied.

    # Arguments

    * `pkg_name` - The name of the package.
    * `extra_name` - The name of the extra/optional dependency.

    # Returns

    * `bool` - True if the extra is satisfied, false otherwise.
    """

def extras_satisfied(pkg_name: builtins.str, extras: typing.Sequence[builtins.str]) -> builtins.bool:
    r"""Checks if all specified extras (optional dependencies) of a Python package are satisfied.

    # Arguments

    * `pkg_name` - The name of the package.
    * `extras` - A vector containing the names of the extras/optional dependencies.

    # Returns

    * `bool` - True if all extras are satisfied, false otherwise.
    """

def is_arabic(string: builtins.str) -> builtins.bool: ...
def is_chinese(string: builtins.str) -> builtins.bool: ...
def is_dutch(string: builtins.str) -> builtins.bool: ...
def is_english(string: builtins.str) -> builtins.bool: ...
def is_french(string: builtins.str) -> builtins.bool: ...
def is_german(string: builtins.str) -> builtins.bool: ...
def is_hindi(string: builtins.str) -> builtins.bool: ...
def is_installed(pkg_name: builtins.str) -> builtins.bool:
    r"""Checks if a Python package is installed.

    # Arguments

    * `pkg_name` - The name of the package to check.

    # Returns

    * `bool` - True if the package is installed, false otherwise.
    """

def is_italian(string: builtins.str) -> builtins.bool: ...
def is_japanese(string: builtins.str) -> builtins.bool: ...
def is_korean(string: builtins.str) -> builtins.bool: ...
def is_likely_text(path: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool:
    r"""Judge if a file is likely text, dir or path not exist are considered false."""

def is_portuguese(string: builtins.str) -> builtins.bool: ...
def is_russian(string: builtins.str) -> builtins.bool: ...
def is_swedish(string: builtins.str) -> builtins.bool: ...
def is_turkish(string: builtins.str) -> builtins.bool: ...
def is_vietnamese(string: builtins.str) -> builtins.bool: ...
def list_installed() -> builtins.list[builtins.str]:
    r"""Lists all installed Python packages.

    # Returns

    * `Vec<String>` - A vector containing the names of all installed packages.
    """

def split_into_chunks(
    string: builtins.str, max_chunk_size: builtins.int, max_overlapping_rate: builtins.float = 0.3
) -> builtins.list[builtins.str]:
    r"""Splits a given string into chunks based on the specified maximum chunk size and overlapping rate.

    The function prioritizes splitting at sentence boundaries. If a sentence exceeds the maximum chunk size,
    it will be split into smaller parts. The overlapping rate determines how much overlap there should be
    between consecutive chunks.

    # Parameters
    - `string`: The input string to be split.
    - `max_chunk_size`: The maximum number of words allowed in a chunk.
    - `max_overlapping_rate`: The rate of overlapping between consecutive chunks, expressed as a fraction of the chunk size.

    # Returns
    A vector of strings, where each string is a chunk of the original input.
    """

def split_sentence_bounds(string: builtins.str) -> builtins.list[builtins.str]:
    r"""Split the string into sentences."""

def split_word_bounds(string: builtins.str) -> builtins.list[builtins.str]:
    r"""Split the string into words."""

def tokens_of(text: builtins.str) -> builtins.int:
    r"""Count tokens of a text."""

def word_count(string: builtins.str) -> builtins.int:
    r"""Count the words."""
