# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing

__all__ = [
    "fork",
]


def fork(repo_path: builtins.str | os.PathLike | pathlib.Path, to: builtins.str | os.PathLike | pathlib.Path,
         branch_name: builtins.str, base_branch: typing.Optional[builtins.str] = None,
         exist_ok: builtins.bool = False) -> pathlib.Path:
    r"""
    Safely forks a new worktree.
    1. Pre-checks branch conflicts and path existence.
    2. Creates branch if missing.
    3. Adds worktree with cleanup on failure.
    """
