[package]
name = "tei_client"
version = "0.1.0"
edition = "2021"

[lib]
name = "tei_client"
crate-type = ["cdylib"]  # For PyO3

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
tonic = "0.13.0"
tokio = "1.44.2"


[build-dependencies]
tonic-build = "0.9"
