[package]
name = "fabricatio-capabilities"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
whichlang = "0.1.1"

pyo3 = { version = "0.24.2", features = ["extension-module"] }





[workspace]