[package]
name = "deck_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
genanki-rs = "0.4.0"
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
walkdir = "2.5.0"
