[package]
name = "deck_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
genanki-rs-rev = { git = "https://github.com/Whth/genanki-rs-rev" }
csv = "1.3.1"
serde = { version = "1.0.227", features = ["derive"] }
serde_yaml2 = "0.1.3"
walkdir = "2.5.0"
