[project]
name = "fabricatio-locale"
version = "0.1.1-dev2"
description = "An extension of fabricatio, which brings up the capability to generate locolization based on po file."
readme = "README.md"
authors = [
    { name = "Whth", email = "zettainspector@foxmail.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.12,<3.14"
dependencies = [

    "fabricatio-core",
    "fabricatio-translate",
    
]

[dependency-groups]
dev = [
    "pytest",
]



[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "fabricatio_locale.rust"


[project.urls]
Homepage = "https://github.com/Whth/fabricatio"
Repository = "https://github.com/Whth/fabricatio"
Issues = "https://github.com/Whth/fabricatio/issues"
