# This file is automatically generated by pyo3_stub_gen

import builtins
import enum
import typing

__all__ = [
    "ProviderType",
    "add_tei",
]

@typing.final
class ProviderType(enum.Enum):
    r"""Enum representing supported LLM provider types.

    Use this enum to specify which type of provider to create
    when calling [`create_provider`].

    # Variants

    * `OpenAI` - Official OpenAI API provider. Requires an API key,
      falls back to `OPENAI_API_KEY` environment variable.
    * `OpenAICompatible` - Any OpenAI API-compatible provider (Azure OpenAI,
      LocalAI, custom endpoints). Requires name, API key, and endpoint URL.
    * `Dummy` - A provider that doesn't make real HTTP calls. Useful for
      testing and development.
    """

    OpenAI = ...
    r"""
    Official OpenAI API provider.
    """
    OpenAICompatible = ...
    r"""
    OpenAI API-compatible provider (Azure, LocalAI, custom endpoints).
    """
    Dummy = ...
    r"""
    Dummy provider for testing (does not make real HTTP calls).
    """

def add_tei(name: builtins.str, url: builtins.str) -> None: ...
