[project]
name = "fabricatio-rule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fabricatio-core"

]



[tool.uv.sources]
fabricatio-core = { workspace = true }