# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

__all__ = [
    "Msg",
    "read_pofile",
    "update_pofile",
]

@typing.final
class Msg:
    @property
    def id(self) -> builtins.str: ...
    @property
    def txt(self) -> builtins.str: ...
    def __new__(cls, id: builtins.str, txt: builtins.str) -> Msg:
        r"""Creates a new Msg instance.

        Args:
            id: The message identifier (msgid).
            txt: The message translation (msgstr).
        """

def read_pofile(file_path: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[Msg]:
    r"""Reads a .po file and returns a vector of Message objects containing msgid and msgstr."""

def update_pofile(file_path: builtins.str | os.PathLike | pathlib.Path, messages: typing.Sequence[Msg]) -> None:
    r"""Updates a .po file with the provided messages.

    Args:
        file_path: Path to the .po file.
        messages: A vector of Message objects containing msgid and msgstr.
    """
