[project]
name = "fabricatio-tool"
version = "0.6.4"
description = "An extension of fabricatio, which brings up the capability to use tool with native python."
readme = "README.md"
authors = [
    { name = "Whth", email = "zettainspector@foxmail.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Framework :: AsyncIO",
    "Framework :: Pydantic :: 2",
    "Typing :: Typed",
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "fabricatio-core",
    "pydantic>=2.11.7",
    "questionary>=2.1.0",
]

[dependency-groups]
dev = [
    "pytest",
]



[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "fabricatio_tool.rust"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[[tool.uv.index]]
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"


[project.urls]
Homepage = "https://github.com/Whth/fabricatio"
Repository = "https://github.com/Whth/fabricatio"
Issues = "https://github.com/Whth/fabricatio/issues"
