[project]
name = "fabricatio-capable"
version = "0.1.1-dev4"
description = "An extension of fabricatio"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Whth", email = "zettainspector@foxmail.com" }
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]

requires-python = ">=3.12,<3.14"

dependencies = [
    "fabricatio-core",
    "fabricatio-tool",
    "fabricatio-judge",
]

[dependency-groups]
dev = [
    "pytest",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
sources = ["python"]

[project.urls]
Homepage = "https://github.com/Whth/fabricatio"
Repository = "https://github.com/Whth/fabricatio"
Issues = "https://github.com/Whth/fabricatio/issues"
