# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "add_csv_data",
    "compile_deck",
    "create_deck_project",
    "extract_html_component",
    "fname_santitize",
    "save_metadata",
    "save_template",
]

def add_csv_data(project_path: builtins.str | os.PathLike | pathlib.Path, model_name: builtins.str, data: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Adds CSV data to an Anki deck project.
    
    Args:
        project_path: The path to the Anki deck project.
        model_name: The name of the model to add data to.
        data: The path to the CSV file.
    
    Returns:
        PyResult<()> indicating success.
    """

def compile_deck(path: builtins.str | os.PathLike | pathlib.Path, output: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Compiles an Anki deck from a path to an output file.
    
    Args:
        path: The path to the Anki deck.
        output: The output file path.
    
    Returns:
        PyResult<()> indicating success.
    """

def create_deck_project(path: builtins.str | os.PathLike | pathlib.Path, deck_name: typing.Optional[builtins.str], deck_description: typing.Optional[builtins.str], author: typing.Optional[builtins.str], model_name: typing.Optional[builtins.str], fields: typing.Optional[typing.Sequence[builtins.str]]) -> None:
    r"""
    Creates a new Anki deck project with the given configuration.
    
    Args:
        path: The directory path for the project.
        deck_name: Optional name for the deck.
        deck_description: Optional description for the deck.
        author: Optional author name.
        model_name: Optional model name.
        fields: Optional list of field names.
    
    Returns:
        PyResult<()> indicating success.
    """

def extract_html_component(html: builtins.str) -> tuple[builtins.str, builtins.str, builtins.str]:
    r"""
    Extracts JavaScript, CSS, and layout components from an HTML string.
    
    Args:
        html: The full HTML content.
    
    Returns:
        A tuple containing (layout, javascript_content, css_content).
        - layout: HTML content without script and style sections
        - javascript_content: Extracted from script tags
        - css_content: Extracted from style tags
    """

def fname_santitize(filename: builtins.str) -> builtins.str: ...

def save_metadata(dir_path: builtins.str | os.PathLike | pathlib.Path, name: builtins.str, data: typing.Any) -> None:
    r"""
    Saves metadata to a YAML file in the specified directory.
    
    Args:
        dir_path: The directory path.
        name: The name for the metadata file (without extension).
        data: The Python object to serialize as YAML.
    
    Returns:
        PyResult<()> indicating success.
    """

def save_template(dir_path: builtins.str | os.PathLike | pathlib.Path, front: builtins.str, back: builtins.str, css: typing.Optional[builtins.str] = None) -> None:
    r"""
    Saves Anki card templates (front, back, and optional CSS) to files.
    
    Args:
        dir_path: The directory to save templates in.
        front: The front template content.
        back: The back template content.
        css: Optional CSS content.
    
    Returns:
        PyResult<()> indicating success.
    """

