[package]
name = "signify"
version = "0.1.0"
edition = "2024"

[dependencies]
heck = "0.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
indoc = "2.0.6"
