# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

__all__ = [
    "start_service",
]

def start_service(
    frontend_dir: builtins.str | os.PathLike | pathlib.Path,
    data_dir: builtins.str | os.PathLike | pathlib.Path,
    addr: builtins.str,
    node_registry_json: builtins.str,
    allowed_origins: typing.Sequence[builtins.str],
) -> typing.Awaitable[None]:
    r"""Starts the web UI service with the given frontend and data directories."""
