# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "start_service",
]

def start_service(frontend_dir: builtins.str | os.PathLike | pathlib.Path, addr: builtins.str) -> typing.Any:
    r"""
    Starts the web UI service with the given frontend directory.
    """

