# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

__all__ = [
    "MAX_IMPORTANCE_SCORE",
    "MIN_IMPORTANCE_SCORE",
    "Memory",
    "MemoryService",
    "MemoryStats",
    "MemoryStore",
]

MAX_IMPORTANCE_SCORE: builtins.int = 100
MIN_IMPORTANCE_SCORE: builtins.int = 0

@typing.final
class Memory:
    r"""Represents a memory object with content, importance, tags, and access statistics."""
    @property
    def uuid(self) -> builtins.str:
        r"""Unique identifier for the memory."""
    @property
    def content(self) -> builtins.str:
        r"""Content of the memory."""
    @property
    def timestamp(self) -> builtins.int:
        r"""Unix timestamp when the memory was created."""
    @property
    def importance(self) -> builtins.int:
        r"""Importance score of the memory (0 to MAX_IMPORTANCE_SCORE)."""
    @property
    def tags(self) -> builtins.list[builtins.str]:
        r"""List of tags associated with the memory."""
    @property
    def access_count(self) -> builtins.int:
        r"""Number of times the memory has been accessed."""
    @property
    def last_accessed(self) -> builtins.int:
        r"""Unix timestamp when the memory was last accessed."""
    def to_dict(self) -> dict:
        r"""Convert the memory to a Python dictionary."""

@typing.final
class MemoryService:
    r"""Service class for managing memory stores and indexes."""
    def __new__(
        cls,
        store_root_directory: builtins.str | os.PathLike | pathlib.Path,
        writer_buffer_size: builtins.int = 15000000,
        cache_size: builtins.int = 10,
    ) -> MemoryService:
        r"""Creates a new MemoryService instance.

        Args:
            store_root_directory (pathlib.Path): The root directory where indexes will be stored.
            writer_buffer_size (int, optional): The buffer size for index writers in bytes. Defaults to 15,000,000 (15MB).
            cache_size (int, optional): The maximum number of indexes to keep in cache. Defaults to 10.

        Returns:
            MemoryService: A new instance of the MemoryService.
        """
    def get_store(self, store_name: builtins.str) -> MemoryStore:
        r"""Gets a MemoryStore instance for the given store name.

        This method retrieves or creates an index for the given store name,
        then returns a MemoryStore instance that can be used to perform
        operations on that index.

        Args:
            store_name (str): The name of the store to get.

        Returns:
            MemoryStore: A MemoryStore instance for the given store name.

        Raises:
            Exception: If the store name is invalid, if there's an error creating or opening the index,
                       or if there's an error creating the MemoryStore instance.
        """
    def list_stores(self, cached_only: builtins.bool = False) -> builtins.list[builtins.str]:
        r"""Lists all stores in the system.

        This method returns a list of all store names. It can optionally return
        only the stores that are currently cached in memory.

        Args:
            cached_only (bool, optional): If True, only return stores that are currently cached in memory.
                                          If False (default), return all stores in the store directory.

        Returns:
            list[str]: A list of store names.

        Raises:
            Exception: If there's an error reading the store directory.
        """

@typing.final
class MemoryStats:
    r"""Memory statistics structure containing aggregated metrics about stored memories."""
    @property
    def total_memories(self) -> builtins.int:
        r"""Total number of memories stored."""
    @property
    def avg_importance(self) -> builtins.float:
        r"""Average importance score across all memories."""
    @property
    def avg_access_count(self) -> builtins.float:
        r"""Average number of times memories have been accessed."""
    @property
    def avg_age_days(self) -> builtins.float:
        r"""Average age of memories in days."""
    def display(self) -> builtins.str:
        r"""Display memory statistics in a formatted string."""

@typing.final
class MemoryStore:
    r"""MemoryStore is a struct that provides an interface for storing, retrieving, and searching memories in a Tantivy search index.

    It supports operations such as adding, updating, deleting, and searching
    memories based on various criteria like content, tags, importance, recency, and access frequency.

    The store handles memory access tracking by updating access counts and timestamps automatically
    during retrieval and search operations. It also supports batch updates and optional immediate
    disk writes for consistency.

    The implementation uses a Tantivy index with fields for content, tags, importance, timestamps,
    and access counts. It includes PyO3 bindings to allow Python usage.
    """
    def add_memory(
        self,
        content: builtins.str,
        importance: builtins.int,
        tags: typing.Sequence[builtins.str],
        write: builtins.bool = False,
    ) -> builtins.str:
        r"""Adds a new memory to the system and returns its unique ID.

        Args:
            content (str): The text content of the memory.
            importance (int): The importance score of the memory.
            tags (list[str]): A list of tags associated with the memory.
            write (bool, optional): If True, commits the changes to disk immediately. Defaults to False.

        Returns:
            str: The UUID of the newly added memory.

        Raises:
            Exception: If there is an error adding the memory or writing to the index.
        """
    def write(self) -> None:
        r"""Writes all pending changes to disk.

        Returns:
            None

        Raises:
            Exception: If there is an error committing the changes.
        """
    def get_memory(self, uuid: builtins.str, write: builtins.bool = False) -> typing.Optional[Memory]:
        r"""Retrieves a memory by its ID and updates its access count.

        Args:
            uuid (str): The unique identifier of the memory.
            write (bool, optional): If True, commits the access update to disk immediately. Defaults to False.

        Returns:
            Memory | None: The retrieved Memory object, or None if not found.

        Raises:
            Exception: If there is an error retrieving the memory or updating the index.
        """
    def update_memory(
        self,
        uuid: builtins.str,
        content: typing.Optional[builtins.str] = None,
        importance: typing.Optional[builtins.int] = None,
        tags: typing.Optional[typing.Sequence[builtins.str]] = None,
        write: builtins.bool = False,
    ) -> builtins.bool:
        r"""Updates an existing memory's content, importance, or tags.

        Args:
            uuid (str): The unique identifier of the memory to update.
            content (str | None, optional): The new content. Defaults to None.
            importance (int | None, optional): The new importance score. Defaults to None.
            tags (list[str] | None, optional): The new list of tags. Defaults to None.
            write (bool, optional): If True, commits the changes to disk immediately. Defaults to False.

        Returns:
            bool: True if the memory was found and updated, False otherwise.

        Raises:
            Exception: If there is an error updating the memory or writing to the index.
        """
    def delete_memory(self, uuid: builtins.str, write: builtins.bool = False) -> builtins.bool:
        r"""Deletes a memory by its ID.

        Args:
            uuid (str): The unique identifier of the memory to delete.
            write (bool, optional): If True, commits the deletion to disk immediately. Defaults to False.

        Returns:
            bool: True if the deletion operation was processed (returns True even if memory didn't exist).

        Raises:
            Exception: If there is an error deleting the memory or writing to the index.
        """
    def search_memories(
        self,
        query_str: builtins.str,
        top_k: builtins.int = 20,
        boost_recent: builtins.bool = False,
        write: builtins.bool = False,
    ) -> builtins.list[Memory]:
        r"""Searches memories by query string with optional recency boosting.

        Args:
            query_str (str): The search query string.
            top_k (int, optional): The maximum number of results to return. Defaults to 20.
            boost_recent (bool, optional): If True, boosts the score of more recent memories. Defaults to False.
            write (bool, optional): If True, commits access updates to disk immediately. Defaults to False.

        Returns:
            list[Memory]: A list of matching Memory objects, sorted by relevance.

        Raises:
            Exception: If there is an error parsing the query or searching the index.
        """
    def search_by_tags(
        self, tags: typing.Sequence[builtins.str], top_k: builtins.int = 20, write: builtins.bool = False
    ) -> builtins.list[Memory]:
        r"""Searches memories by specific tags.

        Args:
            tags (list[str]): A list of tags to search for. Memories matching any of these tags will be returned.
            top_k (int, optional): The maximum number of results to return. Defaults to 20.
            write (bool, optional): If True, commits access updates to disk immediately. Defaults to False.

        Returns:
            list[Memory]: A list of matching Memory objects.

        Raises:
            Exception: If there is an error searching the index.
        """
    def get_memories_by_importance(
        self, min_importance: builtins.int, top_k: builtins.int = 20, write: builtins.bool = False
    ) -> builtins.list[Memory]:
        r"""Gets memories filtered by a minimum importance level.

        Args:
            min_importance (int): The minimum importance score.
            top_k (int, optional): The maximum number of results to return. Defaults to 20.
            write (bool, optional): If True, commits access updates to disk immediately. Defaults to False.

        Returns:
            list[Memory]: A list of Memory objects with importance >= min_importance.

        Raises:
            Exception: If there is an error searching the index.
        """
    def get_recent_memories(
        self, days: builtins.int, top_k: builtins.int = 20, write: builtins.bool = False
    ) -> builtins.list[Memory]:
        r"""Gets memories from the last N days.

        Args:
            days (int): The number of days to look back.
            top_k (int, optional): The maximum number of results to return. Defaults to 20.
            write (bool, optional): If True, commits access updates to disk immediately. Defaults to False.

        Returns:
            list[Memory]: A list of Memory objects created within the last N days.

        Raises:
            Exception: If there is an error searching the index.
        """
    def get_frequently_accessed(self, top_k: builtins.int = 20, write: builtins.bool = False) -> builtins.list[Memory]:
        r"""Gets memories sorted by access frequency (most accessed first).

        Args:
            top_k (int, optional): The maximum number of results to return. Defaults to 20.
            write (bool, optional): If True, commits access updates to disk immediately. Defaults to False.

        Returns:
            list[Memory]: A list of Memory objects sorted by access count in descending order.

        Raises:
            Exception: If there is an error searching the index.
        """
    def count_memories(self) -> builtins.int:
        r"""Counts the total number of memories in the system.

        Returns:
            int: The total number of documents in the index.
        """
    def stats(self) -> MemoryStats:
        r"""Gets aggregated statistics about all memories.

        Returns:
            MemoryStats: An object containing total memories, average importance,
                         average access count, and average age in days.

        Raises:
            Exception: If there is an error calculating aggregations.
        """
