[project]
name = "fabricatio-core"
version = "0.3.6"
description = "A foundational Python library providing core components for building LLM-driven applications using an event-based agent structure."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Whth", email = "zettainspector@foxmail.com" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "asyncio>=3.4.3",
    "asyncstdlib>=3.13.0",
    "json-repair>=0.39.1",
    "litellm>=1.60.0",
    "loguru>=0.7.3",
    "more-itertools>=10.6.0",
    "pydantic>=2.10.6",
    "pymitter>=1.0.0",
    "rich>=13.9.4",
    "orjson>=3.10.18",
]
[project.optional-dependencies]
full = [
    "fabricatio-core[ftd,qa]",
]


qa = [
    "questionary>=2.1.0",
]
ftd = [
    "magika>=0.6.1",
]

[dependency-groups]
dev = [
    "pytest",
]




[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "fabricatio_core.rust"



[project.urls]
Homepage = "https://github.com/Whth/fabricatio"
Repository = "https://github.com/Whth/fabricatio"
Issues = "https://github.com/Whth/fabricatio/issues"
