# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

__all__ = [
    "CheckConfig",
    "MCPManager",
    "ToolMetaData",
    "gather_violations",
    "treeview",
]

@typing.final
class CheckConfig:
    r"""Configuration for checks, specifying the mode and target items."""
    def __new__(cls, targets: builtins.set[builtins.str], mode: builtins.str = "whitelist") -> CheckConfig:
        r"""Create a new CheckConfig instance with specified targets and mode."""

@typing.final
class MCPManager:
    r"""Python-exposed MCP manager."""
    @staticmethod
    def create(server_configs: dict) -> typing.Any:
        r"""Creates a new MCP manager instance.

        Args:
            server_configs: Python dictionary containing server configurations.

        Returns:
            An awaitable that resolves to a new MCPManager instance.
        """
    def list_tools(self, client_id: builtins.str) -> typing.Any:
        r"""Retrieves list of tools from a client.

        Args:
            client_id: The ID of the client.

        Returns:
            An awaitable that resolves to a list of ToolMetaData objects.
        """
    def get_tool(self, client_id: builtins.str, tool_name: builtins.str) -> typing.Any:
        r"""Retrieves a tool from a client.

        Args:
            client_id: The ID of the client.
            tool_name: The name of the tool.

        Returns:
            An awaitable that resolves to a ToolMetaData object or None.
        """
    def list_tool_names(self, client_id: builtins.str) -> typing.Any:
        r"""Retrieves a list of tool names from a client.

        Args:
            client_id: The ID of the client to retrieve tools from.

        Returns:
            An awaitable that resolves to a list of tool names.
        """
    def description_mapping(self, client_id: builtins.str) -> typing.Any:
        r"""Retrieves a mapping of tool names to their descriptions from a client.

        Args:
            client_id: The ID of the client.

        Returns:
            An awaitable that resolves to a dict mapping tool names to descriptions.
        """
    def server_list(self) -> builtins.list[builtins.str]:
        r"""Returns a list of all server names currently managed by the MCP manager.

        Returns:
            A list of server names.
        """
    def server_count(self) -> builtins.int:
        r"""Returns the number of servers currently managed by the MCP manager.

        Returns:
            The number of servers.
        """
    def ping(self, client_id: builtins.str) -> typing.Any:
        r"""Checks if a client is still connected and responsive.

        Args:
            client_id: The ID of the client to ping.

        Returns:
            An awaitable that resolves to True if connected, False otherwise.
        """
    def call_tool(
        self, client_id: builtins.str, tool_name: builtins.str, arguments: typing.Optional[dict]
    ) -> typing.Any:
        r"""Executes a tool on a client and returns the result.

        Args:
            client_id: The ID of the client.
            tool_name: The name of the tool to execute.
            arguments: Optional dictionary of tool arguments.

        Returns:
            An awaitable that resolves to a list of result strings.
        """
    def has_client(self, client_id: builtins.str) -> builtins.bool:
        r"""Checks if a client exists in the manager.

        Args:
            client_id: The ID of the client to check.

        Returns:
            True if the client exists, False otherwise.
        """
    def has_tool(self, client_id: builtins.str, tool_name: builtins.str) -> typing.Any:
        r"""Checks if a tool exists for a specific client.

        Args:
            client_id: The ID of the client.
            tool_name: The name of the tool to check.

        Returns:
            An awaitable that resolves to True if the tool exists, False otherwise.
        """

@typing.final
class ToolMetaData:
    r"""Python representation of tool metadata."""
    @property
    def name(self) -> builtins.str:
        r"""Returns the name of the tool.

        Returns:
            The tool name as a string.
        """
    @property
    def description(self) -> builtins.str:
        r"""Returns the description of the tool.

        Returns:
            The tool description as a string.
        """
    @property
    def input_schema(self) -> typing.Any:
        r"""Returns the input schema as a Python object.

        Returns:
            The input schema as a Python object.
        """
    @property
    def input_schema_string(self) -> builtins.str:
        r"""Returns the input schema as a JSON string.

        Returns:
            The input schema as a JSON string.
        """
    @property
    def annotations(self) -> typing.Any:
        r"""Returns the annotations as a Python object.

        Returns:
            The annotations as a Python object.
        """
    @property
    def annotations_string(self) -> builtins.str:
        r"""Returns the annotations as a JSON string.

        Returns:
            The annotations as a JSON string.
        """
    @property
    def function_header(self) -> builtins.str:
        r"""Returns the function signature header.

        Returns:
            The function signature as a string.
        """
    @property
    def function_docstring(self) -> builtins.str:
        r"""Returns the function docstring.

        Returns:
            The function docstring as a string.
        """
    @property
    def function_string(self) -> builtins.str:
        r"""Returns the complete function string with header and docstring.

        Returns:
            The complete function definition as a string.
        """
    def dump_dict(self) -> typing.Any:
        r"""Serializes the tool metadata to a Python dictionary.

        Returns:
            A Python dictionary representation of the tool metadata.
        """

def gather_violations(
    source: builtins.str,
    modules: typing.Optional[CheckConfig] = None,
    imports: typing.Optional[CheckConfig] = None,
    calls: typing.Optional[CheckConfig] = None,
) -> builtins.list[builtins.str]:
    r"""Gathers violations in the provided source code based on the given configuration."""

def treeview(
    directory: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, max_depth: builtins.int = 10
) -> builtins.str:
    r"""Generates a tree-like string representation of a directory structure.

    Skips hidden files and respects .gitignore.

    Args:
        directory: Root path to visualize (default: current directory).
        max_depth: Maximum depth to traverse (default: 10).

    Returns:
        A formatted string resembling the Unix `tree` command output.
    """
