"""Document models for storing LLM-enriched text chunks in LanceDB."""

from typing import ClassVar, Type

from fabricatio_lancedb.capabilities.lancedb import LancedbAddRAGConfig, LancedbFetchRAGConfig
from fabricatio_lancedb.models.lancedb import LancedbDocumentModel
from fabricatio_lancedb.rust import SearchedDocument, StoreDocument

from fabricatio_novel.config import novel_config


class EnrichedDocument(LancedbDocumentModel[StoreDocument, SearchedDocument]):
    """Semantic marker for enriched text chunks stored in LanceDB.

    Each instance stores the flattened text of one or more question-answer
    pairs generated by `EnrichChunkTextNovel.enrich`.
    """

    rendering_template: ClassVar[str] = novel_config.enriched_as_prompt_template


class EnrichedFetchConfig(LancedbFetchRAGConfig[EnrichedDocument]):
    """Fetch configuration for enriched documents."""

    document_model: Type[EnrichedDocument] = EnrichedDocument


class EnrichedAddConfig(LancedbAddRAGConfig):
    """Add configuration for enriched documents."""
