[package]
name = "tools"
edition = "2024"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
tex2typst-rs = "0.4.1"

typst_conversion = { path = "../typst_conversion" }

[[bin]]
name = "ttm"
path = "src/bin/convert_to_typst_math.rs"

