# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "BibManager",
    "comment",
    "convert_all_tex_math",
    "extract_body",
    "extract_sections",
    "fix_misplaced_labels",
    "replace_thesis_body",
    "split_out_metadata",
    "strip_comment",
    "tex_to_typst",
    "to_metadata",
    "uncomment",
]

@typing.final
class BibManager:
    def __new__(cls, path: builtins.str) -> BibManager:
        r"""Create a new BibManager instance."""
    def get_cite_key_by_title(self, title: builtins.str) -> typing.Optional[builtins.str]:
        r"""Find the cite key of an article with given title."""
    def get_cite_key_by_title_fuzzy(self, title: builtins.str) -> typing.Optional[builtins.str]: ...
    def get_cite_key_fuzzy(self, query: builtins.str) -> typing.Optional[builtins.str]:
        r"""Find the corresponding cite key of an article with given query string using fuzzy matcher."""
    def list_titles(self, is_verbatim: builtins.bool = False) -> builtins.list[builtins.str]: ...
    def get_author_by_key(self, key: builtins.str) -> typing.Optional[builtins.list[builtins.str]]: ...
    def get_year_by_key(self, key: builtins.str) -> typing.Optional[builtins.int]: ...
    def get_abstract_by_key(self, key: builtins.str) -> typing.Optional[builtins.str]: ...
    def get_title_by_key(self, key: builtins.str) -> typing.Optional[builtins.str]: ...
    def get_field_by_key(self, key: builtins.str, field: builtins.str) -> typing.Optional[builtins.str]: ...

def comment(string: builtins.str) -> builtins.str:
    r"""Adds comment prefix `//` to each line of the string.

    Args:
        string: The input string to comment.

    Returns:
        A string with `//` prepended to each line.
    """

def convert_all_tex_math(string: builtins.str) -> builtins.str:
    r"""Converts all supported TeX math expressions in a string to Typst format.

    Handles $...$, $$...$$, \(...\), and \[...\] delimiters.

    Args:
        string: The input string containing TeX math expressions.

    Returns:
        A PyResult containing the string with converted math expressions.
    """

def extract_body(string: builtins.str, wrapper: builtins.str) -> typing.Optional[builtins.str]:
    r"""Extracts the body content enclosed by exactly two wrapper strings.

    Args:
        string: The string containing the wrapped body.
        wrapper: The wrapper string that marks the beginning and end.

    Returns:
        The body content if exactly one match found, None otherwise.
    """

def extract_sections(
    string: builtins.str, level: builtins.int = 1, section_char: builtins.str = "#"
) -> builtins.list[tuple[builtins.str, builtins.str]]:
    r"""Extracts sections from markdown-style text by header level.

    Args:
        string: The markdown text to parse.
        level: The header level to extract (e.g., 1 for #, 2 for ##).
        section_char: Optional character to use as header marker (default: #).

    Returns:
        A list of tuples containing (header_text, section_content).
    """

def fix_misplaced_labels(string: builtins.str) -> builtins.str:
    r"""Fixes misplaced labels in a string by moving them outside display math blocks.

    Labels in the format <label> that appear inside \[...\] blocks are moved
    to outside the block.

    Args:
        string: The input string to fix.

    Returns:
        A string with misplaced labels moved outside display math blocks.
    """

def replace_thesis_body(
    string: builtins.str, wrapper: builtins.str, new_body: builtins.str
) -> typing.Optional[builtins.str]:
    r"""Replaces the body content enclosed by two wrapper strings.

    Args:
        string: The original string containing the wrapped body.
        wrapper: The wrapper string that marks the beginning and end.
        new_body: The new body content to insert.

    Returns:
        The string with the body replaced, or None if wrapper not found.
    """

def split_out_metadata(string: builtins.str) -> tuple[typing.Optional[typing.Any], builtins.str]:
    r"""Splits metadata (YAML front matter) from a Typst document string.

    Extracts leading comment lines as YAML metadata and returns the remaining content.

    Args:
        string: The input string with potential YAML front matter.

    Returns:
        A tuple of (parsed metadata as Python object or None, remaining string content).
    """

def strip_comment(string: builtins.str) -> builtins.str:
    r"""Removes leading and trailing comment lines from a multi-line string.

    Args:
        string: The input string to strip comments from.

    Returns:
        A string with leading and trailing comment lines removed.
    """

def tex_to_typst(string: builtins.str) -> builtins.str:
    r"""Converts a raw LaTeX string to Typst format.

    Args:
        string: The raw LaTeX string to convert.

    Returns:
        A PyResult containing the converted Typst string.
    """

def to_metadata(data: typing.Any) -> builtins.str:
    r"""Converts a Python object to a YAML string with comment formatting.

    Args:
        data: The Python object to convert.

    Returns:
        A PyResult containing the YAML string with `//` comments.
    """

def uncomment(string: builtins.str) -> builtins.str:
    r"""Removes comment prefix `//` from each line of the string.

    Args:
        string: The input string to uncomment.

    Returns:
        A string with comment prefixes removed from each line.
    """
