# This file is automatically generated by pyo3_stub_gen

import builtins
import os
import pathlib
import typing

MAX_IMPORTANCE_SCORE: builtins.int
MIN_IMPORTANCE_SCORE: builtins.int

@typing.final
class Memory:
    @property
    def uuid(self) -> builtins.str: ...
    @property
    def content(self) -> builtins.str: ...
    @property
    def timestamp(self) -> builtins.int: ...
    @property
    def importance(self) -> builtins.int: ...
    @property
    def tags(self) -> builtins.list[builtins.str]: ...
    @property
    def access_count(self) -> builtins.int: ...
    @property
    def last_accessed(self) -> builtins.int: ...
    def to_dict(self) -> dict: ...

@typing.final
class MemoryService:
    def __new__(
        cls,
        store_root_directory: builtins.str | os.PathLike | pathlib.Path,
        writer_buffer_size: builtins.int = 50000000,
        cache_size: builtins.int = 10,
    ) -> MemoryService:
        r"""Create a new MemorySystem with optional index path and writer buffer size."""
    def get_store(self, store_name: builtins.str) -> MemoryStore: ...
    def list_stores(self, cached_only: builtins.bool = False) -> builtins.list[builtins.str]: ...

@typing.final
class MemoryStats:
    @property
    def total_memories(self) -> builtins.int: ...
    @property
    def avg_importance(self) -> builtins.float: ...
    @property
    def avg_access_count(self) -> builtins.float: ...
    @property
    def avg_age_days(self) -> builtins.float: ...
    def display(self) -> builtins.str:
        r"""Display memory statistics in a formatted string."""

@typing.final
class MemoryStore:
    def add_memory(
        self, content: builtins.str, importance: builtins.int, tags: typing.Sequence[builtins.str]
    ) -> builtins.str:
        r"""Add a new memory to the system and return its ID."""
    def get_memory(self, uuid: builtins.str) -> typing.Optional[Memory]:
        r"""Retrieve a memory by its ID and update its access count."""
    def update_memory(
        self,
        uuid: builtins.str,
        content: typing.Optional[builtins.str] = None,
        importance: typing.Optional[builtins.int] = None,
        tags: typing.Optional[typing.Sequence[builtins.str]] = None,
    ) -> builtins.bool:
        r"""Update an existing memory's content, importance, or tags."""
    def delete_memory(self, uuid: builtins.str) -> builtins.bool:
        r"""Delete a memory by its ID."""
    def search_memories(
        self, query_str: builtins.str, top_k: builtins.int = 20, boost_recent: builtins.bool = False
    ) -> builtins.list[Memory]:
        r"""Search memories by query string with optional recency boosting."""
    def search_by_tags(self, tags: typing.Sequence[builtins.str], top_k: builtins.int = 20) -> builtins.list[Memory]:
        r"""Search memories by tags."""
    def get_memories_by_importance(
        self, min_importance: builtins.int, top_k: builtins.int = 20
    ) -> builtins.list[Memory]:
        r"""Get memories filtered by minimum importance level."""
    def get_recent_memories(self, days: builtins.int, top_k: builtins.int = 20) -> builtins.list[Memory]:
        r"""Get memories from the last N days."""
    def get_frequently_accessed(self, top_k: builtins.int = 20) -> builtins.list[Memory]:
        r"""Get memories sorted by access frequency."""
    def count_memories(self) -> builtins.int:
        r"""Count the total number of memories in the system."""
    def stats(self) -> MemoryStats:
        r"""Get aggregated statistics about all memories."""
