[package]
name = "fabricatio-router"
version = "0.1.8"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thryd = { path = "../thryd", features = ["pyo3", "jev"] }
jevlin = { path = "../jevlin", default-features = false }
fabricatio-config = { path = "../fabricatio-config" }
fabricatio-logger = { path = "../fabricatio-logger" }
fabricatio-constants = { path = "../fabricatio-constants" }
error-mapping = { workspace = true, features = ["thryd", "jevlin", "std", "serde_json"] }
pyo3 = { version = "0.29.2" }
pyo3-async-runtimes = { version = "0.29.0", features = ["tokio-runtime"] }
pyo3-stub-gen = "0.23.0"
futures = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
blake3 = "1.8.7"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
webp = { version = "0.3.1", default-features = false }

[features]
default = ["pyo3/extension-module"]
stubgen = ["thryd/stubgen", "fabricatio-logger/stubgen", "fabricatio-config/stubgen"]
