"""Models defined in fabricatio-rag."""

from typing import List

from fabricatio_core.models.generic import SketchedAble


class QAPair(SketchedAble):
    """A question-answer pair where the answer is grounded in source text."""

    question: str
    """The question that can be answered by the source text passage below."""
    answer: str
    """The source text passage that provides the answer to the question above."""


class EnrichmentResult(SketchedAble):
    """Container holding all question-answer pairs generated for one text chunk."""

    qa_pairs: List[QAPair]
    """Question-answer pairs generated by enriching a single text chunk."""
