# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

__all__ = [
    "SearchedDocument",
    "StoreDocument",
    "VectorStoreService",
    "VectorStoreTable",
]

@typing.final
class SearchedDocument:
    r"""Represents a document that has been searched and retrieved from the vector store.

    This structure contains the core information of a searched document including
    its unique identifier, content, timestamp of creation/modification, and any
    associated metadata stored as JSON string.
    """
    @property
    def id(self) -> builtins.str:
        r"""Unique identifier for the document, typically generated as a UUID string."""
    @property
    def content(self) -> builtins.str:
        r"""The textual content of the document that was searched and matched."""
    @property
    def timestamp(self) -> builtins.int:
        r"""Timestamp indicating when the document was created or last updated."""
    @property
    def metadata(self) -> typing.Optional[builtins.str]:
        r"""Optional metadata associated with the document, stored as a JSON string.

        This can include additional contextual information about the document.
        """
    def access_metadata(self) -> dict:
        r"""Access the metadata of the document.

        Returns a Python dictionary representation of the document's metadata.
        If no metadata exists, returns an empty dictionary.
        """

@typing.final
class StoreDocument:
    @property
    def content(self) -> builtins.str: ...
    @content.setter
    def content(self, value: builtins.str) -> None: ...
    @property
    def vector(self) -> builtins.list[builtins.float]: ...
    @vector.setter
    def vector(self, value: typing.Sequence[builtins.float]) -> None: ...
    @property
    def metadata(self) -> typing.Optional[builtins.str]: ...
    @metadata.setter
    def metadata(self, value: typing.Optional[builtins.str]) -> None: ...
    def __new__(
        cls, content: builtins.str, vector: typing.Sequence[builtins.float], metadata: typing.Optional[builtins.str]
    ) -> StoreDocument:
        r"""Create a new Document instance."""
    @staticmethod
    def with_metadata(
        content: builtins.str, vector: typing.Sequence[builtins.float], metadata: typing.Optional[dict]
    ) -> StoreDocument:
        r"""Create a new Document instance with metadata dict."""

@typing.final
class VectorStoreService:
    r"""A service for managing vector stores using LanceDB.

    This service provides methods for connecting to a LanceDB instance,
    creating tables, opening existing tables, and creating or opening tables.
    It acts as a high-level interface for vector store operations.
    """
    @staticmethod
    def connect(uri: builtins.str) -> typing.Awaitable[typing.Self]:
        r"""Connect to a lancedb instance."""
    def create_table(self, table_name: builtins.str, ndim: builtins.int) -> typing.Awaitable[VectorStoreTable]:
        r"""Create a table."""
    def open_table(self, table_name: builtins.str) -> typing.Awaitable[VectorStoreTable]:
        r"""Open a table."""
    def create_or_open_table(self, table_name: builtins.str, ndim: builtins.int) -> typing.Awaitable[VectorStoreTable]:
        r"""Create or open a table."""

@typing.final
class VectorStoreTable:
    def add_documents(
        self, documents: list[StoreDocument], rebuild_index: builtins.bool = True
    ) -> typing.Awaitable[builtins.list[builtins.str]]:
        r"""Adds multiple documents to the vector store.

        Args:
            documents: A list of StoreDocument objects to be added to the store.
            rebuild_index: If True (default), rebuild the vector index after adding. Set to False for bulk inserts.

        Returns:
            An awaitable that resolves to a list of document IDs.
        """

    def rebuild_index(self) -> typing.Awaitable[None]:
        r"""Rebuilds the vector index on the table.

        Useful after bulk inserts with ``rebuild_index=False``.
        No-op if the table has fewer than 256 rows (minimum for PQ training).
        """
    def search_document(
        self, embedding: typing.Sequence[builtins.float], limit: builtins.int
    ) -> typing.Awaitable[builtins.list[SearchedDocument]]:
        r"""Searches for documents similar to the given embedding vector.

        Args:
            embedding: A vector representing the query embedding for similarity search.
            limit: The maximum number of similar documents to return.

        Returns:
            An awaitable that resolves to a list of SearchedDocument objects.
        """
